apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ososrb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: osos-role
subjects:
- kind: ServiceAccount
  name: osos-sa
  namespace: osos

